spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.4.42.216:3306/blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: (WZ137124)root
    filters: log4j,wall,mergeStat
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
logging:
  level.root: info
  level.com.next.jiangzh: debug
  path: logs/
  file: next-film.log
server:
  port: 8081
